import Layout from '@/components/layout'
import { NextAuthProvider } from './nextAuthProvider'
import { ThemeProvider } from '@/components/themeProvider'
import { ShoppingCartContextProvider } from '@/context/shoppingCart'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <NextAuthProvider>
          <ThemeProvider>
            <ShoppingCartContextProvider>
              <Layout>{children}</Layout>
            </ShoppingCartContextProvider>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
