import Layout from '@/components/layout'
import { NextAuthProvider } from './nextAuthProvider'
import { ThemeProvider } from '@/components/themeProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ThemeProvider>
          <NextAuthProvider>
            <Layout>{children}</Layout>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
